### ISSUE TITLE
Specific code for Sketch Analysis

### ISSUE THREAD

**Issue by ifdita-hasan** [zachzeyuwang/tracing-vs-freehand#1]
My team and I are currently working with 2D building sketches and are taking inspiration from your paper, "Tracing Versus Freehand for Evaluating Computer-Generated Drawing." We are particularly interested in the drawing analysis techniques/algorithms used in the paper, as we intend to carry out similar analyses on our 2D sketch filters. However, after checking the GitHub repository for your project, we were unable to find any code scripts related to the analysis.
Could you please provide the specific code used for the analysis of the tables and figures in the attached images? We would greatly appreciate your attention to this request, as we are working towards a tight deadline.

![image](https://github.com/user-attachments/assets/f69f4419-a91e-41ba-8b73-217ae0f0a088)

![image](https://github.com/user-attachments/assets/652cac23-81e6-4c87-baf0-d5d4ec10847f)

**Comment by zachzeyuwang** [comment]
Hi there, to compute the precision and recall in Fig. 9, you first need to use the [rtsc](https://rtsc.cs.princeton.edu/) package to generate a series of NPR line drawings with varying thresholds. Then for each type of NPR (SC, RV, AR) or image-based method (Canny, HED), you can use our code to compute the precision and recall given a hand-drawn sketch and a series of synthetic line drawings with varying thresholds. We will clean our code and get back to you soon.

**Comment by zachzeyuwang** [comment]
[2_nprlines_tmp.zip](https://github.com/user-attachments/files/16577024/2_nprlines_tmp.zip)

Here is the code I wrote for the precision and recall analysis. Once you have all the hand-drawn and NPR line drawings in place, you can run `find_npr_num_pixels.py` and `precision_recall_vector.cpp` to compute the precision and recall. Hope this helps with catching your deadline. I'll update this repository later with cleaned code and documentation.

**Comment by ifdita-hasan** [comment]
Thank you so much for your swift response! We really appreciate it!
